export enum Colors {
  TRANSPARENT = 'transparent',
  WHITE = '#FFFFFF',
  BLACK_MAIN = '#252232',
  BLACK_MAIN_80 = 'rgba(37, 34, 50, 0.8)',
  BLUE_MAIN = '#0088E9',
  BLUE_HOVER = '#3AA1EB',
  BLUE_BORDER = '#D3E0EF',
  BLUE_BACK = '#EEF4FB',
  GREY_MIDDLE_GRIDS = '#68788D',
  GREY_DESCRIPTOR = '#919399',
  GREY_INACTIVE = '#C0C2C9',
  GREY_TWO = '#EDEEF2',
  GREY_BACKGROUND = '#F9FAFD',
  RED_MAIN = '#EA5959',
  GREEN_MAIN = '#2F929A',
  YELLOW_MAIN = '#E5A139',
}

export enum DefaultColors {
  // ------- ALL APP ------- //
  BACKGROUND = Colors.GREY_BACKGROUND,
  APP_BACKGROUND = Colors.GREY_BACKGROUND,
  ICON_HEADER = Colors.BLACK_MAIN,
  LIGHT_BORDER = Colors.GREY_INACTIVE,
  BLUE_BORDER = Colors.BLUE_BORDER,
  BLUE_LIGHT_BORDER = Colors.BLUE_BACK,

  // ------- TEXT ------- //
  LINK_TEXT = Colors.BLUE_MAIN,
  BASE_TEXT = Colors.BLACK_MAIN,
  SECONDARY_TEXT = Colors.GREY_DESCRIPTOR,
  TERTIARY_TEXT = Colors.GREY_INACTIVE,
  ERROR_TEXT = Colors.RED_MAIN,

  // ------- BUTTONS ------- //
  // --- main --- //
  STATIC_BUTTONS = Colors.BLUE_MAIN,
  DISABLE_STATIC_BUTTONS = Colors.GREY_INACTIVE,
  STATIC_BUTTONS_TEXT = Colors.WHITE,
  DISABLE_STATIC_BUTTONS_TEXT = Colors.WHITE,
  PRESSED_BUTTONS = Colors.BLUE_HOVER,
  // --- secondary --- //
  STATIC_SECONDARY_BUTTONS = Colors.BLUE_MAIN,
  DISABLE_STATIC_SECONDARY_BUTTONS = Colors.GREY_INACTIVE,
  STATIC_SECONDARY_BUTTONS_TEXT = Colors.WHITE,
  DISABLE_STATIC_SECONDARY_BUTTONS_TEXT = Colors.WHITE,
  PRESSED_SECONDARY_BUTTONS = Colors.BLUE_HOVER,
  // --- transparent --- //
  TRANSPARENT_BUTTONS = Colors.TRANSPARENT,
  TRANSPARENT_TEXT = Colors.BLUE_MAIN,
  DISABLE_TRANSPARENT_BUTTONS_TEXT = Colors.GREY_INACTIVE,
  PRESSED_TRANSPARENT_BUTTONS = Colors.BLUE_BACK,
  // --- border --- //
  BORDER_BUTTON = Colors.TRANSPARENT,
  BORDER_BUTTON_BORDER = Colors.BLUE_MAIN,
  DISABLED_BORDER_BUTTON_BORDER = Colors.GREY_INACTIVE,
  PRESSED_BORDER_BUTTON = Colors.BLUE_BACK,

  // --- INPUTS --- //
  PLACEHOLDER_INPUT = Colors.GREY_DESCRIPTOR,
  DISABLE_PLACEHOLDER_INPUT = Colors.GREY_INACTIVE,
  BACKGROUND_INPUT = Colors.WHITE,
  BACKGROUND_DISABLE_INPUT = Colors.GREY_TWO,
  BORDER_INPUT = Colors.BLUE_BORDER,
  BORDER_FOCUSED_INPUT = Colors.BLUE_MAIN,
  TRANSPARENT_INPUT = Colors.TRANSPARENT,
  ERROR_INPUT = Colors.RED_MAIN,

  // ------- TOAST ------- //
  TOAST_ERROR = Colors.RED_MAIN,
  TOAST_WARNING = Colors.YELLOW_MAIN,
  TOAST_SUCCESS = Colors.GREEN_MAIN,
  SMALL_TOAST_BACKGROUND = Colors.BLACK_MAIN_80,
  SMALL_TOAST_TEXT = Colors.WHITE,

  // Home //
  ACTIVE_STATUS_CIRCLE = Colors.BLUE_MAIN,
  ACTIVE_STATUS_TEXT = Colors.WHITE,
  STEP_CARD_BACKGROUND = Colors.WHITE,
}

export enum DarkColors {
  // ------- ALL APP ------- //
  BACKGROUND = Colors.GREY_BACKGROUND,
  APP_BACKGROUND = Colors.GREY_BACKGROUND,
  ICON_HEADER = Colors.BLACK_MAIN,
  LIGHT_BORDER = Colors.GREY_INACTIVE,
  BLUE_BORDER = Colors.BLUE_BORDER,

  // ------- TEXT ------- //
  LINK_TEXT = Colors.BLUE_MAIN,
  BASE_TEXT = Colors.BLACK_MAIN,
  SECONDARY_TEXT = Colors.GREY_DESCRIPTOR,
  TERTIARY_TEXT = Colors.GREY_INACTIVE,
  ERROR_TEXT = Colors.RED_MAIN,

  // ------- BUTTONS ------- //
  // --- main --- //
  STATIC_BUTTONS = Colors.BLUE_MAIN,
  DISABLE_STATIC_BUTTONS = Colors.GREY_INACTIVE,
  STATIC_BUTTONS_TEXT = Colors.WHITE,
  DISABLE_STATIC_BUTTONS_TEXT = Colors.WHITE,
  PRESSED_BUTTONS = Colors.BLUE_HOVER,
  // --- secondary --- //
  STATIC_SECONDARY_BUTTONS = Colors.BLUE_MAIN,
  DISABLE_STATIC_SECONDARY_BUTTONS = Colors.GREY_INACTIVE,
  STATIC_SECONDARY_BUTTONS_TEXT = Colors.WHITE,
  DISABLE_STATIC_SECONDARY_BUTTONS_TEXT = Colors.WHITE,
  PRESSED_SECONDARY_BUTTONS = Colors.BLUE_HOVER,
  // --- transparent --- //
  TRANSPARENT_BUTTONS = Colors.TRANSPARENT,
  TRANSPARENT_TEXT = Colors.BLUE_MAIN,
  DISABLE_TRANSPARENT_BUTTONS_TEXT = Colors.GREY_INACTIVE,
  PRESSED_TRANSPARENT_BUTTONS = Colors.BLUE_BACK,
  // --- border --- //
  BORDER_BUTTON = Colors.TRANSPARENT,
  BORDER_BUTTON_BORDER = Colors.BLUE_MAIN,
  DISABLED_BORDER_BUTTON_BORDER = Colors.GREY_INACTIVE,
  PRESSED_BORDER_BUTTON = Colors.BLUE_BACK,

  // --- INPUTS --- //
  PLACEHOLDER_INPUT = Colors.GREY_DESCRIPTOR,
  DISABLE_PLACEHOLDER_INPUT = Colors.GREY_INACTIVE,
  BACKGROUND_INPUT = Colors.WHITE,
  BACKGROUND_DISABLE_INPUT = Colors.GREY_TWO,
  BORDER_INPUT = Colors.BLUE_BORDER,
  BORDER_FOCUSED_INPUT = Colors.BLUE_MAIN,
  TRANSPARENT_INPUT = Colors.TRANSPARENT,
  ERROR_INPUT = Colors.RED_MAIN,

  // ------- TOAST ------- //
  TOAST_ERROR = Colors.RED_MAIN,
  TOAST_WARNING = Colors.YELLOW_MAIN,
  TOAST_SUCCESS = Colors.GREEN_MAIN,
  SMALL_TOAST_BACKGROUND = Colors.BLACK_MAIN_80,
  SMALL_TOAST_TEXT = Colors.WHITE,

  // Home //
  ACTIVE_STATUS_CIRCLE = Colors.BLUE_MAIN,
  ACTIVE_STATUS_TEXT = Colors.WHITE,
  STEP_CARD_BACKGROUND = Colors.WHITE,
}
